spring.datasource.url=jdbc:postgresql://localhost:5433/baile_namorados
spring.datasource.username=baile
spring.datasource.password=baile123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false